<a href="https://colab.research.google.com/github/Mubashir-Hussain-025/MACHINE-LEARNING-CYBERSECURITY-/blob/main/MACHINE_LEARNING_CYBERSECURITY_IRIS_DATASET_CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import pandas as pd
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import svm
from sklearn.preprocessing import LabelEncoder , StandardScaler # Corrected the import name

In [146]:
feature=genfromtxt("/content/Iris.csv",delimiter=',',usecols=(i for i in range (0,4)),dtype=float,skip_header=1)
class_value=genfromtxt("/content/Iris.csv",delimiter=',',usecols=(-1),dtype=str,skip_header=1)


In [147]:
scaler = StandardScaler()
labels=LabelEncoder().fit_transform(class_value)
feature_std=scaler.fit_transform(feature)
x_train,x_test,y_train,y_test=train_test_split(feature_std,labels,test_size=0.3,random_state=0)

In [148]:
precision_scores_list=[]
accuracy_scores_list=[]
recall_scores_list=[]
f1_scores_list=[]

In [149]:
def print_stats_metrics(y_test, y_pred):
    print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
    accuracy_scores_list.append(accuracy_score(y_test, y_pred))
    confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
    print("confusion matrix")
    print(confmat)
    print(pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True))
    precision_scores_list.append(precision_score(y_true=y_test, y_pred=y_pred, average='weighted'))
    print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=y_pred, average='weighted'))
    print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=y_pred, average='weighted'))
    print('F1-measure: %.3f' % f1_score(y_true=y_test, y_pred=y_pred, average='weighted'))

In [150]:
##########################Support Vector Machine##########################
print("##########################Support Vector Machine##########################")
clfSvm = svm.SVC(gamma='scale')
clfSvm.fit(x_train,y_train)
predictions = clfSvm.predict(x_test)
print_stats_metrics(y_test, predictions)

##########################Logistic Regression##########################
print("##########################Logistic Regression##########################")
clfLog = LogisticRegression(solver='lbfgs', multi_class='auto')
clfLog.fit(x_train,y_train)
predictions = clfLog.predict(x_test)
print_stats_metrics(y_test, predictions)

##########################Decision Tree##########################
print("##########################Decision Tree##########################")
clfDT = DecisionTreeRegressor()
clfDT.fit(x_train,y_train)
predictions = clfDT.predict(x_test)
print_stats_metrics(y_test, predictions)

##########################Random Forest##########################
print("##########################Random Forest##########################")
clfRF = RandomForestClassifier()
clfRF.fit(x_train,y_train)
predictions = clfRF.predict(x_test)
print_stats_metrics(y_test, predictions)

##########################Support Vector Machine##########################
Accuracy: 1.00
confusion matrix
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Predicted   0   1   2  All
True                      
0          16   0   0   16
1           0  18   0   18
2           0   0  11   11
All        16  18  11   45
Precision: 1.000
Recall: 1.000
F1-measure: 1.000
##########################Logistic Regression##########################
Accuracy: 1.00
confusion matrix
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Predicted   0   1   2  All
True                      
0          16   0   0   16
1           0  18   0   18
2           0   0  11   11
All        16  18  11   45
Precision: 1.000
Recall: 1.000
F1-measure: 1.000
##########################Decision Tree##########################
Accuracy: 0.98
confusion matrix
[[16  0  0]
 [ 0 18  0]
 [ 0  1 10]]
Predicted  0.0  1.0  2.0  All
True                         
0           16    0    0   16
1            0   18    0   18
2            0    1   10   11
All     

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Accuracy: 1.00
confusion matrix
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Predicted   0   1   2  All
True                      
0          16   0   0   16
1           0  18   0   18
2           0   0  11   11
All        16  18  11   45
Precision: 1.000
Recall: 1.000
F1-measure: 1.000
